title: ThePaleBlue<i style='color:cyan;' title='dot'>.</i>dev
remote_theme: daattali/beautiful-jekyll@6.0.1
avatar: public/img/avatar.jpg


navbar-links:
  Home: "index"
  About Me: "aboutme"

navbar-col: "#333333"
navbar-text-col: "#AAAAAA"


