title: ThePaleBlue<i style='color:cyan;'>.</i>dev
remote_theme: daattali/beautiful-jekyll@6.0.1


navbar-links:
  Home: "index"

navbar-col: "#333333"
navbar-text-col: "#AAAAAA"


css:
  - public/css/video.css
